[resource]
cat = { dark = [
    "resources/cat/dark_cat_0.ico",
    "resources/cat/dark_cat_1.ico",
    "resources/cat/dark_cat_2.ico",
    "resources/cat/dark_cat_3.ico",
    "resources/cat/dark_cat_4.ico",
], light = [
    "resources/cat/light_cat_0.ico",
    "resources/cat/light_cat_1.ico",
    "resources/cat/light_cat_2.ico",
    "resources/cat/light_cat_3.ico",
    "resources/cat/light_cat_4.ico",
] }

horse = { dark = [
    "resources/horse/dark_horse_0.ico",
    "resources/horse/dark_horse_1.ico",
    "resources/horse/dark_horse_2.ico",
    "resources/horse/dark_horse_3.ico",
    "resources/horse/dark_horse_4.ico",
], light = [
    "resources/horse/light_horse_0.ico",
    "resources/horse/light_horse_1.ico",
    "resources/horse/light_horse_2.ico",
    "resources/horse/light_horse_3.ico",
    "resources/horse/light_horse_4.ico",
] }

parrot = { dark = [
    "resources/parrot/dark_parrot_0.ico",
    "resources/parrot/dark_parrot_1.ico",
    "resources/parrot/dark_parrot_2.ico",
    "resources/parrot/dark_parrot_3.ico",
    "resources/parrot/dark_parrot_4.ico",
], light = [
    "resources/parrot/light_parrot_0.ico",
    "resources/parrot/light_parrot_1.ico",
    "resources/parrot/light_parrot_2.ico",
    "resources/parrot/light_parrot_3.ico",
    "resources/parrot/light_parrot_4.ico",
] }
