[resource]
cat = { dark = [
    "resources/cat/dark_cat_0.ico",
    "resources/cat/dark_cat_1.ico",
    "resources/cat/dark_cat_2.ico",
    "resources/cat/dark_cat_3.ico",
    "resources/cat/dark_cat_4.ico",
], light = [
    "resources/cat/light_cat_0.ico",
    "resources/cat/light_cat_1.ico",
    "resources/cat/light_cat_2.ico",
    "resources/cat/light_cat_3.ico",
    "resources/cat/light_cat_4.ico",
] }

dance = { dark = [
    "resources/dance/dark_dance_0.ico",
    "resources/dance/dark_dance_1.ico",
    "resources/dance/dark_dance_2.ico",
    "resources/dance/dark_dance_3.ico",
    "resources/dance/dark_dance_4.ico",
], light = [
    "resources/dance/light_dance_0.ico",
    "resources/dance/light_dance_1.ico",
    "resources/dance/light_dance_2.ico",
    "resources/dance/light_dance_3.ico",
    "resources/dance/light_dance_4.ico",
] }
